package shmdebug










































































}	fmt.Printf("UnaryCall succeeded! Response payload size: %d\n", len(resp.Payload.Body))	}		return		fmt.Printf("UnaryCall failed: %v\n", err)	if err != nil {	resp, err := client.UnaryCall(ctx, req)	fmt.Println("Making UnaryCall...")	}		Payload:      payload,		ResponseSize: int32(100),		ResponseType: payload.Type,	req := &testpb.SimpleRequest{	payload := benchmark.NewPayload(testpb.PayloadType_COMPRESSABLE, 100)	defer cancel()	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)	// Make a simple unary call	client := testgrpc.NewBenchmarkServiceClient(conn)	fmt.Println("Client connected")	defer conn.Close()	}		return		fmt.Printf("Failed to dial: %v\n", err)	if err != nil {	conn, err := grpc.NewClient(target, dialOpts...)	}		grpc.WithTransportCredentials(insecure.NewCredentials()),		grpc.WithShmTransport(),	dialOpts := []grpc.DialOption{	target := fmt.Sprintf("shm://%s", name)	// Dial using SHM transport	fmt.Println("Server started")	defer stopSrv()	stopSrv := benchmark.StartServer(benchmark.ServerInfo{Type: "protobuf", Listener: lis})	// Start server using benchmark package	fmt.Printf("Listener created: %s\n", lis.Addr().String())	defer transport.RemoveSegment(name)	defer lis.Close()	}		return		fmt.Printf("Failed to create listener: %v\n", err)	if err != nil {	lis, err := transport.NewShmListener(&transport.ShmAddr{Name: name}, 64*1024*1024, 64*1024*1024, 64*1024*1024)	name := fmt.Sprintf("debug_shm_%d", time.Now().UnixNano())	// Create a shared memory listenerfunc main() {)	testpb "google.golang.org/grpc/interop/grpc_testing"	testgrpc "google.golang.org/grpc/interop/grpc_testing"	"google.golang.org/grpc/internal/transport"	"google.golang.org/grpc/credentials/insecure"	"google.golang.org/grpc/benchmark"	"google.golang.org/grpc"	"time"	"fmt"	"context"import (package main//go:build linux